require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProverbesController do

  # This should return the minimal set of attributes required to create a valid
  # Proverbe. As you add validations to Proverbe, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProverbesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all proverbes as @proverbes" do
      proverbe = Proverbe.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proverbes).should eq([proverbe])
    end
  end

  describe "GET show" do
    it "assigns the requested proverbe as @proverbe" do
      proverbe = Proverbe.create! valid_attributes
      get :show, {:id => proverbe.to_param}, valid_session
      assigns(:proverbe).should eq(proverbe)
    end
  end

  describe "GET new" do
    it "assigns a new proverbe as @proverbe" do
      get :new, {}, valid_session
      assigns(:proverbe).should be_a_new(Proverbe)
    end
  end

  describe "GET edit" do
    it "assigns the requested proverbe as @proverbe" do
      proverbe = Proverbe.create! valid_attributes
      get :edit, {:id => proverbe.to_param}, valid_session
      assigns(:proverbe).should eq(proverbe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Proverbe" do
        expect {
          post :create, {:proverbe => valid_attributes}, valid_session
        }.to change(Proverbe, :count).by(1)
      end

      it "assigns a newly created proverbe as @proverbe" do
        post :create, {:proverbe => valid_attributes}, valid_session
        assigns(:proverbe).should be_a(Proverbe)
        assigns(:proverbe).should be_persisted
      end

      it "redirects to the created proverbe" do
        post :create, {:proverbe => valid_attributes}, valid_session
        response.should redirect_to(Proverbe.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proverbe as @proverbe" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proverbe.any_instance.stub(:save).and_return(false)
        post :create, {:proverbe => {}}, valid_session
        assigns(:proverbe).should be_a_new(Proverbe)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Proverbe.any_instance.stub(:save).and_return(false)
        post :create, {:proverbe => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proverbe" do
        proverbe = Proverbe.create! valid_attributes
        # Assuming there are no other proverbes in the database, this
        # specifies that the Proverbe created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Proverbe.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => proverbe.to_param, :proverbe => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested proverbe as @proverbe" do
        proverbe = Proverbe.create! valid_attributes
        put :update, {:id => proverbe.to_param, :proverbe => valid_attributes}, valid_session
        assigns(:proverbe).should eq(proverbe)
      end

      it "redirects to the proverbe" do
        proverbe = Proverbe.create! valid_attributes
        put :update, {:id => proverbe.to_param, :proverbe => valid_attributes}, valid_session
        response.should redirect_to(proverbe)
      end
    end

    describe "with invalid params" do
      it "assigns the proverbe as @proverbe" do
        proverbe = Proverbe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proverbe.any_instance.stub(:save).and_return(false)
        put :update, {:id => proverbe.to_param, :proverbe => {}}, valid_session
        assigns(:proverbe).should eq(proverbe)
      end

      it "re-renders the 'edit' template" do
        proverbe = Proverbe.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Proverbe.any_instance.stub(:save).and_return(false)
        put :update, {:id => proverbe.to_param, :proverbe => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proverbe" do
      proverbe = Proverbe.create! valid_attributes
      expect {
        delete :destroy, {:id => proverbe.to_param}, valid_session
      }.to change(Proverbe, :count).by(-1)
    end

    it "redirects to the proverbes list" do
      proverbe = Proverbe.create! valid_attributes
      delete :destroy, {:id => proverbe.to_param}, valid_session
      response.should redirect_to(proverbes_url)
    end
  end

end
